### ISSUE TITLE
Faulty device could not be updated

### ISSUE THREAD

**Issue by alpha23** [EUROTRONIC-Technology/Spirit-ZigBee#12]
Hi,

I used the provided firmware file to update nearly all of my devices. Only the faulty device (where I can not write to 0x4003) don't want to take the firmware file. It just go to status idle and nothing else happens.

When I select and query the device in the STD OTAU Plugin I can see that the faulty device have 0xffff as value for the Vendor and the Image. All other thermostats have the values 0x1037 and 0x110c, which is similar to the values of the firmware file.

<img width="486" alt="Bildschirmfoto 2021-02-13 um 12 34 37" src="https://user-images.githubusercontent.com/1942930/107849125-655fe600-6df9-11eb-834e-b1b16170d4ea.png">
<img width="486" alt="Bildschirmfoto 2021-02-13 um 12 34 21" src="https://user-images.githubusercontent.com/1942930/107849126-66911300-6df9-11eb-8f98-23ee0d987c4a.png">

Two of the working devices also showed the version 20191014 and did not have any problems to write to 0x4003 or take the firmware update.

**Comment by stefangehn** [comment]
There's an ongoing discussion about firmware update problems in #1 that also mentions all-bits-set vendor and image identifiers.

The first (and possibly only) Spirit ZigBee that I bought in January 2021 suffers from the same problem which makes downgrading to the previous working firmware impossible.
